In [39]:
import numpy as np
from keras.models import Model, load_model
from keras.layers import Dense, Input, Dropout, Activation
from keras.layers.normalization import BatchNormalization
from keras.optimizers import adam
from keras.callbacks import EarlyStopping, ModelCheckpoint

In [105]:
X_train=np.load('train_files/X_train.npy', mmap_mode='r')
y_train=np.load('train_files/y_train_k.npy', mmap_mode='r')
X_value = np.load('train_files/X_val.npy', mmap_mode = 'r')
y_value = np.load('train_files/y_val_k.npy', mmap_mode = 'r')

In [106]:
y_value


memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [41]:
mean=np.mean(X_train, axis=0)

In [90]:
std=np.std(X_train,axis=0)
std[std==0]=1
X_train = X_train - mean / std
X_value = X_value - mean / std


In [92]:
ins = Input(shape = (X_train.shape[1],))
x = Dense(4096)(ins)
x = Activation('relu')(x)
x = BatchNormalization()(x)
x = Dense(2048)(x)
x = Activation('relu')(x)
x = BatchNormalization()(x)
x = Dense(1024)(x)
x = Activation('relu')(x)
x = BatchNormalization()(x)
outs = Dense(y_train.shape[1], activation = 'relu')(x)

model = Model(ins, outs)



In [107]:
opt = Adam()
model.compile(opt, 'categorical_crossentropy', metrics = ['acc'])
stopper = EarlyStopping(monitor='value_acc', patience = 4, mode='auto')
checker = ModelCheckpoint('train_files/relu_best.h8', monitor='value_acc', mode='auto')

In [108]:


model.fit(X_train, y_train,
          epochs=100, batch_size=32,
          validation_data=(X_value, y_value),
          callbacks = [stopper, checker])



Train on 62 samples, validate on 13 samples
Epoch 1/100
62/62 [==============================] - 2s 39ms/step - loss: 2.5940 - acc: 0.4355 - val_loss: 6.0062 - val_acc: 0.0000e+00


/home/CORPUSERS/86007937/PycharmProjects/RL/venv/lib/python3.5/site-packages/keras/callbacks.py:526: RuntimeWarning: Early stopping conditioned on metric `value_acc` which is not available. Available metrics are: loss,val_loss,val_acc,acc
  (self.monitor, ','.join(list(logs.keys()))), RuntimeWarning


Epoch 2/100
62/62 [==============================] - 1s 9ms/step - loss: 0.9891 - acc: 0.8710 - val_loss: 5.9828 - val_acc: 0.0000e+00
Epoch 3/100
62/62 [==============================] - 0s 8ms/step - loss: 0.1329 - acc: 1.0000 - val_loss: 5.7785 - val_acc: 0.0000e+00
Epoch 4/100
62/62 [==============================] - 0s 8ms/step - loss: 0.0677 - acc: 1.0000 - val_loss: 5.7748 - val_acc: 0.0000e+00
Epoch 5/100
62/62 [==============================] - 0s 8ms/step - loss: 0.0460 - acc: 0.9839 - val_loss: 5.7830 - val_acc: 0.0000e+00
Epoch 6/100
62/62 [==============================] - 0s 8ms/step - loss: 0.0207 - acc: 1.0000 - val_loss: 5.8554 - val_acc: 0.0000e+00
Epoch 7/100
62/62 [==============================] - 0s 7ms/step - loss: 0.0309 - acc: 1.0000 - val_loss: 5.9274 - val_acc: 0.0000e+00
Epoch 8/100
62/62 [==============================] - 0s 8ms/step - loss: 0.0132 - acc: 1.0000 - val_loss: 5.8556 - val_acc: 0.0000e+00
Epoch 9/100
62/62 [==============================] - 1s

62/62 [==============================] - 0s 7ms/step - loss: 2.9646e-05 - acc: 1.0000 - val_loss: 5.5683 - val_acc: 0.0000e+00
Epoch 62/100
62/62 [==============================] - 0s 8ms/step - loss: 2.6409e-05 - acc: 1.0000 - val_loss: 5.5710 - val_acc: 0.0000e+00
Epoch 63/100
62/62 [==============================] - 1s 8ms/step - loss: 3.0417e-05 - acc: 1.0000 - val_loss: 5.5742 - val_acc: 0.0000e+00
Epoch 64/100
62/62 [==============================] - 0s 8ms/step - loss: 2.8094e-05 - acc: 1.0000 - val_loss: 5.5760 - val_acc: 0.0000e+00
Epoch 65/100
62/62 [==============================] - 1s 9ms/step - loss: 2.9001e-05 - acc: 1.0000 - val_loss: 5.5802 - val_acc: 0.0000e+00
Epoch 66/100
62/62 [==============================] - 0s 8ms/step - loss: 2.4475e-05 - acc: 1.0000 - val_loss: 5.5851 - val_acc: 0.0000e+00
Epoch 67/100
62/62 [==============================] - 0s 8ms/step - loss: 3.2869e-05 - acc: 1.0000 - val_loss: 5.5888 - val_acc: 0.0000e+00
Epoch 68/100
62/62 [=============

In [109]:
model = load_model('train_files/relu_best.h5')

In [110]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 256)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 4096)              1052672   
_________________________________________________________________
activation_4 (Activation)    (None, 4096)              0         
_________________________________________________________________
batch_normalization_4 (Batch (None, 4096)              16384     
_________________________________________________________________
dense_6 (Dense)              (None, 2048)              8390656   
_________________________________________________________________
activation_5 (Activation)    (None, 2048)              0         
_________________________________________________________________
batch_normalization_5 (Batch (None, 2048)              8192      
__________

In [97]:
from sklearn.metrics import accuracy_score

In [98]:
Value_predicts= model.predict(X_value)
Value_predicts


array([[2.5514478e-03, 2.1826949e-03, 1.1054078e-02, ..., 1.0501348e-03,
        8.2763704e-03, 7.7868142e-04],
       [2.4214631e-03, 3.8514249e-03, 9.6804267e-03, ..., 1.4592613e-03,
        5.4627634e-03, 8.0791482e-04],
       [3.3372545e-01, 1.1900924e-03, 2.4899904e-01, ..., 8.4386074e-06,
        3.9093927e-03, 2.6383254e-04],
       ...,
       [4.3670021e-02, 5.8798149e-04, 3.1326973e-01, ..., 1.9681395e-03,
        1.6593380e-02, 4.3861051e-03],
       [4.3279370e-03, 2.1257850e-03, 1.3717511e-02, ..., 1.0286479e-03,
        1.6914537e-02, 7.9546748e-03],
       [5.1227486e-04, 6.1548217e-03, 3.1907037e-03, ..., 1.6723889e-03,
        2.5697667e-02, 1.3130454e-04]], dtype=float32)

In [99]:
intPredictValue=np.array([np.argmax(r) for r in Value_predicts])

In [100]:
intPredictValue

array([70, 70,  0,  3,  0,  0,  2, 39, 39, 39,  3, 70, 70])

In [101]:
Int_Y_value=np.array([np.argmax(r) for r in y_value])

In [102]:
Int_Y_value

array([58, 59, 16, 36, 11, 13, 19, 50, 57, 51, 23, 47, 68])

In [103]:
val_acc=accuracy_score(Int_Y_value,intPredictValue)

In [104]:
val_acc

0.0