In [23]:
import pandas as pd
import csv
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import scipy as sp
import numpy as np

In [121]:
column_name=['Flow ID' ,'Source IP','Source Port' ,'Destination IP', 'Destination Port', 'Protocol','Timestamp', 'Flow Duration'
            ,'Total Fwd Packets','Total Backward Packets','Total Length of Fwd Packets','Total Length of Bwd Packets', 
            'Fwd Packet Length Max', 'Fwd Packet Length Min', 'Fwd Packet Length Mean', 'Fwd Packet Length Std', 
            'Bwd Packet Length Max', 'Bwd Packet Length Min', 'Bwd Packet Length Mean', 'Bwd Packet Length', 
            'Std Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 
             'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 
             'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min','Fwd PSH Flags','Bwd PSH Flags', 
             'Fwd URG Flags','Bwd URG Flags', 'Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s',
              'Bwd Packets/s', 'Min Packet Length', 'Max Packet Length','Packet Length Mean', 'Packet Length Std', 
              'Packet Length Variance','FIN Flag Count','SYN Flag Count', 'RST Flag Count', 'PSH Flag Count',
             'ACK Flag Count','URG Flag Count','CWE Flag Count','ECE Flag Count','Down/Up Ratio','Average Packet Size',
              'Avg Fwd Segment Size','Avg Bwd Segment Size','Fwd Header Length','Fwd Avg Bytes/Bulk','Fwd Avg Packets/Bulk', 
               'Fwd Avg Bulk Rate','Bwd Avg Bytes/Bulk','Bwd Avg Packets/Bulk','Bwd Avg Bulk Rate','Subflow Fwd Packets' 
              'Subflow Fwd Bytes','Subflow Bwd Packets', 'Subflow Bwd Bytes', 'Init_Win_bytes_forward', 
           'Init_Win_bytes_backward','act_data_pkt_fwd','min_seg_size_forward','Active Mean','Active Std','Active Max','Active Min',
          'Idle Mean','Idle Std','Idle Max','Idle Min','Label']





attribute_num=['Flow ID' ,'Source IP','Source Port' ,'Destination IP', 'Destination Port', 'Protocol','Timestamp', 'Flow Duration',
                        'Total Fwd Packets','Total Backward Packets','Total Length of Fwd Packets','Total Length of Bwd Packets', 
                           'Fwd Packet Length Max', 'Fwd Packet Length Min', 'Fwd Packet Length Mean', 'Fwd Packet Length Std', 
                           'Bwd Packet Length Max', 'Bwd Packet Length Min', 'Bwd Packet Length Mean', 'Bwd Packet Length', 
                           'Std Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 
                           'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 
                           'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd Header Length', 'Bwd Header Length', 
                           'Bwd Packets/s', 'Min Packet Length', 'Max Packet Length','Packet Length Mean', 'Packet Length Std', 
                           'Packet Length Variance','FIN Flag Count','SYN Flag Count', 'RST Flag Count', 'PSH Flag Count',
                           'ACK Flag Count','URG Flag Count','CWE Flag Count','ECE Flag Count','Down/Up Ratio','Average Packet Size',
                           'Avg Fwd Segment Size','Avg Bwd Segment Size','Fwd Header Length','Fwd Avg Bytes/Bulk','Fwd Avg Packets/Bulk', 
                           'Fwd Avg Bulk Rate','Bwd Avg Bytes/Bulk','Bwd Avg Packets/Bulk','Bwd Avg Bulk Rate','Subflow Fwd Packets' 
                           'Subflow Fwd Bytes','act_data_pkt_fwd','min_seg_size_forward','Active Mean','Active Std','Active Max','Active Min',
                           'Idle Mean','Idle Std','Idle Max','Idle Min','Label']








dataset= pd.read_csv("Wednesday-workingHours.pcap_ISCX.csv", low_memory=False)

In [122]:
dataset

Flow ID       Source IP  \
0         192.168.10.14-209.48.71.168-49459-80-6   192.168.10.14   
1         192.168.10.3-192.168.10.17-389-49453-6   192.168.10.17   
2          192.168.10.3-192.168.10.17-88-46124-6   192.168.10.17   
3         192.168.10.3-192.168.10.17-389-49454-6   192.168.10.17   
4          192.168.10.3-192.168.10.17-88-46126-6   192.168.10.17   
5         192.168.10.3-192.168.10.17-389-49460-6   192.168.10.17   
6          192.168.10.3-192.168.10.17-88-46131-6   192.168.10.17   
7         192.168.10.16-91.189.88.161-37380-80-6   192.168.10.16   
8       192.168.10.3-192.168.10.15-49666-49413-6   192.168.10.15   
9       192.168.10.3-192.168.10.15-49666-49413-6    192.168.10.3   
10         192.168.10.3-192.168.10.12-88-49894-6   192.168.10.12   
11        192.168.10.3-192.168.10.12-389-43838-6   192.168.10.12   
12       192.168.10.3-192.168.10.12-3268-59666-6   192.168.10.12   
13       131.253.61.82-192.168.10.15-443-49452-6   192.168.10.15   
14       131.253.61.82-192.168.10.15-443-49452-6   192.168.10.15   
15       192.168.10.3-192.168.10.8-49666-49184-6    192.168.10.8   
16         192.168.10.3-192.168.10.8-135-49183-6    192.168.10.8   
17       192.168.10.3-192.168.10.8-49666-49184-6    192.168.10.8   
18         192.168.10.3-192.168.10.8-135-49183-6    192.168.10.8   
19         192.168.10.15-23.61.187.27-49441-80-6    23.61.187.27   
20      134.170.51.247-192.168.10.14-443-49466-6   192.168.10.14   
21      134.170.51.247-192.168.10.14-443-49468-6   192.168.10.14   
22       192.168.10.14-40.77.226.220-49470-443-6   192.168.10.14   
23       192.168.10.14-40.77.226.220-49470-443-6   192.168.10.14   
24      192.168.10.9-192.168.10.50-13792-44459-6    192.168.10.9   
25      192.168.10.9-192.168.10.50-13792-44459-6   192.168.10.50   
26         192.168.10.9-192.168.10.50-13791-21-6    192.168.10.9   
27         192.168.10.9-192.168.10.50-13791-21-6   192.168.10.50   
28         192.168.10.9-192.168.10.50-13790-22-6    192.168.10.9   
29         192.168.10.9-192.168.10.50-13790-22-6    192.168.10.9   
...                                          ...             ...   
692673       192.168.10.51-23.15.4.10-51621-80-6      23.15.4.10   
692674     192.168.10.3-192.168.10.12-53-4260-17   192.168.10.12   
692675     192.168.10.3-192.168.10.9-53-58610-17    192.168.10.9   
692676   192.168.10.14-52.85.100.130-54714-443-6   52.85.100.130   
692677    192.168.10.3-192.168.10.12-53-26972-17   192.168.10.12   
692678     152.163.13.4-192.168.10.17-80-37907-6    152.163.13.4   
692679    192.168.10.16-104.88.94.36-46098-443-6    104.88.94.36   
692680    192.168.10.3-192.168.10.19-53-29671-17   192.168.10.19   
692681       172.16.0.1-192.168.10.50-45758-80-6      172.16.0.1   
692682      172.217.10.6-192.168.10.8-80-54901-6    172.217.10.6   
692683   192.168.10.25-192.168.10.50-53379-139-6   192.168.10.50   
692684      192.168.10.14-52.84.3.47-56736-443-6      52.84.3.47   
692685     192.168.10.3-192.168.10.5-53-65187-17    192.168.10.5   
692686     192.168.10.3-192.168.10.5-53-58132-17    192.168.10.5   
692687    162.208.22.34-192.168.10.5-443-58891-6   162.208.22.34   
692688      192.168.10.12-52.7.32.18-49032-443-6      52.7.32.18   
692689     192.168.10.3-192.168.10.5-53-63865-17    192.168.10.5   
692690    192.168.10.17-31.13.69.228-58603-443-6   192.168.10.17   
692691   192.168.10.19-23.194.141.47-50882-443-6   192.168.10.19   
692692    192.168.10.3-192.168.10.51-53-45488-17   192.168.10.51   
692693    192.168.10.3-192.168.10.14-53-49378-17   192.168.10.14   
692694      192.168.10.16-72.21.91.29-35450-80-6     72.21.91.29   
692695     192.168.10.3-192.168.10.9-53-53123-17    192.168.10.9   
692696       172.16.0.1-192.168.10.50-45756-80-6      172.16.0.1   
692697    192.168.10.19-113.29.190.10-49346-80-6   113.29.190.10   
692698    192.168.10.3-192.168.10.14-53-51114-17   192.168.10.14   
692699    192.168.10.3-192.168.10.16-53-24054-17   192.168.10.16   
692700  192.168.10.51-23.208.

In [119]:
#feature= dataset[attribute_num].astype(object)
#dataset = pd.DataFrame(np.asarray([list(i) for i in dataset], dtype=object))

In [124]:
label=dataset[' Label']
label

0                BENIGN
1                BENIGN
2                BENIGN
3                BENIGN
4                BENIGN
5                BENIGN
6                BENIGN
7                BENIGN
8                BENIGN
9                BENIGN
10               BENIGN
11               BENIGN
12               BENIGN
13               BENIGN
14               BENIGN
15               BENIGN
16               BENIGN
17               BENIGN
18               BENIGN
19               BENIGN
20               BENIGN
21               BENIGN
22               BENIGN
23               BENIGN
24               BENIGN
25               BENIGN
26               BENIGN
27               BENIGN
28               BENIGN
29               BENIGN
              ...      
692673           BENIGN
692674           BENIGN
692675           BENIGN
692676           BENIGN
692677           BENIGN
692678           BENIGN
692679           BENIGN
692680           BENIGN
692681    DoS GoldenEye
692682           BENIGN
692683          

In [125]:
dataset = pd.DataFrame(np.asarray([list(i) for i in dataset], dtype=object))

In [126]:
dataset

0
0                               [F, l, o, w,  , I, D]
1                      [ , S, o, u, r, c, e,  , I, P]
2                [ , S, o, u, r, c, e,  , P, o, r, t]
3       [ , D, e, s, t, i, n, a, t, i, o, n,  , I, P]
4   [ , D, e, s, t, i, n, a, t, i, o, n,  , P, o, ...
5                         [ , P, r, o, t, o, c, o, l]
6                      [ , T, i, m, e, s, t, a, m, p]
7          [ , F, l, o, w,  , D, u, r, a, t, i, o, n]
8   [ , T, o, t, a, l,  , F, w, d,  , P, a, c, k, ...
9   [ , T, o, t, a, l,  , B, a, c, k, w, a, r, d, ...
10  [T, o, t, a, l,  , L, e, n, g, t, h,  , o, f, ...
11  [ , T, o, t, a, l,  , L, e, n, g, t, h,  , o, ...
12  [ , F, w, d,  , P, a, c, k, e, t,  , L, e, n, ...
13  [ , F, w, d,  , P, a, c, k, e, t,  , L, e, n, ...
14  [ , F, w, d,  , P, a, c, k, e, t,  , L, e, n, ...
15  [ , F, w, d,  , P, a, c, k, e, t,  , L, e, n, ...
16  [B, w, d,  , P, a, c, k, e, t,  , L, e, n, g, ...
17  [ , B, w, d,  , P, a, c, k, e, t,  , L, e, n, ...
18  [ , B, w, d,  , P, a, c, k, e, t,  , L, e, n, ...
19  [ , B, w, d,  , P, a, c, k, e, t,  , L, e, n, ...
20               [F, l, o, w,  , B, y, t, e, s, /, s]
21      [ , F, l, o, w,  , P, a, c, k, e, t, s, /, s]
22         [ , F, l, o, w,  , I, A, T,  , M, e, a, n]
23            [ , F, l, o, w,  , I, A, T,  , S, t, d]
24            [ , F, l, o, w,  , I, A, T,  , M, a, x]
25            [ , F, l, o, w,  , I, A, T,  , M, i, n]
26            [F, w, d,  , I, A, T,  , T, o, t, a, l]
27            [ , F, w, d,  , I, A, T,  , M, e, a, n]
28               [ , F, w, d,  , I, A, T,  , S, t, d]
29               [ , F, w, d,  , I, A, T,  , M, a, x]
..                                                ...
55      [ , C, W, E,  , F, l, a, g,  , C, o, u, n, t]
56      [ , E, C, E,  , F, l, a, g,  , C, o, u, n, t]
57         [ , D, o, w, n, /, U, p,  , R, a, t, i, o]
58  [ , A, v, e, r, a, g, e,  , P, a, c, k, e, t, ...
59  [ , A, v, g,  , F, w, d,  , S, e, g, m, e, n, ...
60  [ , A, v, g,  , B, w, d,  , S, e, g, m, e, n, ...
61  [ , F, w, d,  , H, e, a, d, e, r,  , L, e, n, ...
62  [F, w, d,  , A, v, g,  , B, y, t, e, s, /, B, ...
63  [ , F, w, d,  , A, v, g,  , P, a, c, k, e, t, ...
64  [ , F, w, d,  , A, v, g,  , B, u, l, k,  , R, ...
65  [ , B, w, d,  , A, v, g,  , B, y, t, e, s, /, ...
66  [ , B, w, d,  , A, v, g,  , P, a, c, k, e, t, ...
67  [B, w, d,  , A, v, g,  , B, u, l, k,  , R, a, ...
68  [S, u, b, f, l, o, w,  , F, w, d,  , P, a, c, ...
69  [ , S, u, b, f, l, o, w,  , F, w, d,  , B, y, ...
70  [ , S, u, b, f, l, o, w,  , B, w, d,  , P, a, ...
71  [ , S, u, b, f, l, o, w,  , B, w, d,  , B, y, ...
72  [I, n, i, t, _, W, i, n, _, b, y, t, e, s, _, ...
73  [ , I, n, i, t, _, W, i, n, _, b, y, t, e, s, ...
74  [ , a, c, t, _, d, a, t, a, _, p, k, t, _, f, ...
75  [ , m, i, n, _, s, e, g, _, s, i, z, e, _, f, ...
76                  [A, c, t, i, v, e,  , M, e, a, n]
77                  [ , A, c, t, i, v, e,  , S, t, d]
78                  [ , A, c, t, i, v, e,  , M, a, x]
79                  [ , A, c, t, i, v, e,  , M, i, n]
80                        [I, d, l, e,  , M, e, a, n]
81                        [ , I, d, l, e,  , S, t, d]
82                        [ , I, d, l, e,  , M, a, x]
83                        [ , I, d, l, e,  , M, i, n]
84                                 [ , L, a, b, e, l]

[85 rows x 1 columns]

In [127]:
#label[label!='BENIGN'] = 'ATTACK'

In [258]:
label.value_counts()

BENIGN              440031
DoS Hulk            231073
DoS GoldenEye        10293
DoS slowloris         5796
DoS Slowhttptest      5499
Heartbleed              11
Name:  Label, dtype: int64

In [259]:
#feature.describe()

In [260]:
#dataset = pd.DataFrame(np.asarray([list(i) for i in dataset], dtype=object))

In [261]:
label.shape

(692703,)

In [262]:
label

0                BENIGN
1                BENIGN
2                BENIGN
3                BENIGN
4                BENIGN
5                BENIGN
6                BENIGN
7                BENIGN
8                BENIGN
9                BENIGN
10               BENIGN
11               BENIGN
12               BENIGN
13               BENIGN
14               BENIGN
15               BENIGN
16               BENIGN
17               BENIGN
18               BENIGN
19               BENIGN
20               BENIGN
21               BENIGN
22               BENIGN
23               BENIGN
24               BENIGN
25               BENIGN
26               BENIGN
27               BENIGN
28               BENIGN
29               BENIGN
              ...      
692673           BENIGN
692674           BENIGN
692675           BENIGN
692676           BENIGN
692677           BENIGN
692678           BENIGN
692679           BENIGN
692680           BENIGN
692681    DoS GoldenEye
692682           BENIGN
692683          

In [305]:
label.index

RangeIndex(start=0, stop=692703, step=1)

In [306]:
def one_hot_v():
    attack=np.asarray(list(label))
    all_attack=np.unique(attack)
all_attack

array(['BENIGN', 'DoS GoldenEye', 'DoS Hulk', 'DoS Slowhttptest',
       'DoS slowloris', 'Heartbleed'], dtype='<U16')

In [307]:
print(len(all_attack))

6


In [308]:
cat_columns=[1,2,3,84]


In [309]:
def make_numeric():
    for x in dataset.columns:
        if x in cat_columns:
            continue
            dataset[x] = pd.to_numeric(dataset[x])
    return dataset[x]



In [310]:
from collections import defaultdict
for x in cat_columns:
    d = defaultdict(LabelEncoder)
    dataset_transformed[x]= dataset.apply(lambda x: d[x.name].fit_transform(x))
    
    

In [311]:
dataset_transformed[x]

0     76
1     58
2     59
3     21
4     22
5     55
6     63
7     25
8     65
9     64
10    84
11    66
12    39
13    41
14    40
15    42
16    73
17    16
18    15
19    17
20    75
21    30
22    27
23    29
24    26
25    28
26    78
27    36
28    38
29    35
      ..
55    20
56    24
57    23
58     4
59     6
60     5
61    34
62    77
63    32
64    31
65     7
66     8
67    71
68    83
69    62
70    61
71    60
72    82
73    47
74    68
75    69
76    70
77     3
78     1
79     2
80    81
81    46
82    44
83    45
84    48
Name: 84, Length: 85, dtype: int64

In [312]:
labels=dataset_transformed[84]

In [313]:
dataset_transformed.drop([84],inplace=True, axis=1)

In [314]:
dataset_transformed.columns

Int64Index([0, 1, 2, 3], dtype='int64')

In [315]:
labels.unique()

array([76, 58, 59, 21, 22, 55, 63, 25, 65, 64, 84, 66, 39, 41, 40, 42, 73,
       16, 15, 17, 75, 30, 27, 29, 26, 28, 78, 36, 38, 35, 37, 72, 11, 13,
       10, 12, 79, 14, 43, 19, 33,  9, 80, 18, 50, 49, 52, 53, 54, 74, 57,
       56, 51,  0, 67, 20, 24, 23,  4,  6,  5, 34, 77, 32, 31,  7,  8, 71,
       83, 62, 61, 60, 82, 47, 68, 69, 70,  3,  1,  2, 81, 46, 44, 45, 48])

In [316]:
cat_columns=[1,2,3]

In [317]:
#one_hot_enc=OneHotEncoder(sparse=False)
#one_hot_enc.fit(dataset_transformed[cat_columns])
one_hot_enc = OneHotEncoder(sparse = False)
one_hot_enc.fit(dataset_transformed[cat_columns])
transformed = one_hot_enc.transform(dataset_transformed[cat_columns])




In [318]:
one_hot_enc = OneHotEncoder(sparse = False)
one_hot_enc.fit(labels.values.reshape(-1,1))
labels_k = one_hot_enc.transform(labels.values.reshape(-1,1))

In [319]:
transformed.shape

(85, 255)

In [320]:
labels

0     76
1     58
2     59
3     21
4     22
5     55
6     63
7     25
8     65
9     64
10    84
11    66
12    39
13    41
14    40
15    42
16    73
17    16
18    15
19    17
20    75
21    30
22    27
23    29
24    26
25    28
26    78
27    36
28    38
29    35
      ..
55    20
56    24
57    23
58     4
59     6
60     5
61    34
62    77
63    32
64    31
65     7
66     8
67    71
68    83
69    62
70    61
71    60
72    82
73    47
74    68
75    69
76    70
77     3
78     1
79     2
80    81
81    46
82    44
83    45
84    48
Name: 84, Length: 85, dtype: int64

In [321]:
labels_k

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [322]:
dataset_transformed.drop(cat_columns, axis = 1, inplace = True)

In [323]:
new_dataset= dataset_transformed.values

In [324]:
new_dataset

array([[76],
       [58],
       [59],
       [21],
       [22],
       [55],
       [63],
       [25],
       [65],
       [64],
       [84],
       [66],
       [39],
       [41],
       [40],
       [42],
       [73],
       [16],
       [15],
       [17],
       [75],
       [30],
       [27],
       [29],
       [26],
       [28],
       [78],
       [36],
       [38],
       [35],
       [37],
       [72],
       [11],
       [13],
       [10],
       [12],
       [79],
       [14],
       [43],
       [19],
       [33],
       [ 9],
       [80],
       [18],
       [50],
       [49],
       [52],
       [53],
       [54],
       [74],
       [57],
       [56],
       [51],
       [ 0],
       [67],
       [20],
       [24],
       [23],
       [ 4],
       [ 6],
       [ 5],
       [34],
       [77],
       [32],
       [31],
       [ 7],
       [ 8],
       [71],
       [83],
       [62],
       [61],
       [60],
       [82],
       [47],
       [68],
       [69],
       [70],

In [325]:
new_dataset = np.concatenate((new_dataset, transformed), axis = 1)

In [354]:
main_msk = np.random.uniform(size = new_dataset.shape[0]) < 0.7
main_msk

array([ True, False,  True, False, False,  True, False, False,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True])

In [327]:
np.save('main_splitting_mask.npy', main_msk)

In [328]:
main_msk.shape

(85,)

In [329]:
main_msk = np.load('main_splitting_mask.npy')

In [330]:


X_train = new_dataset[main_msk, :]
y_train = labels[main_msk]
y_train_k = labels_k[main_msk]
new_dataset = new_dataset[~main_msk, :]
labels = labels[~main_msk]
labels_k = labels_k[~main_msk]



In [335]:


sub_msk = np.random.uniform(size = new_dataset.shape[0]) < 0.5
np.save('sub_splitting_mask.npy', sub_msk)
sub_msk = np.load('sub_splitting_mask.npy')



In [336]:
X_value = new_dataset[sub_msk, :]
y_value = labels[sub_msk]
y_value_k = labels_k[sub_msk]


In [339]:
np.save('train_files/X_train.npy', X_train)
np.save('train_files/y_val_k.npy', y_value_k)
np.save('train_files/X_test.npy', new_dataset[~sub_msk,:])
np.save('train_files/y_test.npy', labels[~sub_msk])
np.save('train_files/y_test_k.npy', labels_k[~sub_msk])
np.save('train_files/y_train.npy', y_train)
np.save('train_files/y_train_k.npy', y_train_k)
np.save('train_files/X_val.npy', X_value)
np.save('train_files/y_val.npy', y_value)
